---
language: node_js
node_js:
  - "6"

sudo: required

addons:
  chrome: stable

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - yarn install --non-interactive --pure-lockfile

script:
  - npm test
